[workspace]
resolver = "2"
members = [
    "examples/rust", # 2.0.0
    "yellowstone-grpc-client", # 2.0.0
    "yellowstone-grpc-geyser", # 2.0.0
    "yellowstone-grpc-proto", # 2.0.0
]

[workspace.package]
authors = ["Triton One"]
edition = "2021"
homepage = "https://triton.one"
repository = "https://github.com/rpcpool/yellowstone-grpc"
license = "AGPL-3.0"
keywords = ["solana"]
publish = false

[workspace.dependencies]
agave-geyser-plugin-interface = "~2.0.10"
anyhow = "1.0.62"
backoff = "0.4.0"
base64 = "0.22.1"
bincode = "1.3.3"
bs58 = "0.5.1"
bytes = "1.3.0"
cargo-lock = "9.0.0"
chrono = "0.4.26"
clap = "4.3.0"
crossbeam-channel = "0.5.8"
env_logger = "0.11.3"
futures = "0.3.24"
git-version = "0.3.5"
hex = "0.4.3"
hostname = "0.4.0"
http = "1.1.0"
http-body-util = "0.1.2"
hyper = "1.4.1"
hyper-util = "0.1.7"
lazy_static = "1.4.0"
local-ip-address = "0.6.1"
log = "0.4.17"
maplit = "1.0.2"
prometheus = "0.13.2"
prost = "0.13.1"
protobuf-src = "1.1.0"
scylla = "0.13.0"
serde = "1.0.145"
serde_json = "1.0.86"
solana-account-decoder = "~2.0.9"
solana-logger = "~2.0.9"
solana-sdk = "~2.0.9"
solana-transaction-status = "~2.0.9"
spl-token-2022 = "4.0.0"
thiserror = "1.0"
tokio = "1.21.2"
tokio-stream = "0.1.11"
tonic = "0.12.1"
tonic-build = "0.12.1"
tonic-health = "0.12.1"
vergen = "9.0.0"
yellowstone-grpc-client = { path = "yellowstone-grpc-client", version = "2.0.0" }
yellowstone-grpc-proto = { path = "yellowstone-grpc-proto", version = "2.0.0", default-features = false }

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"

[profile.release]
lto = true
codegen-units = 1

# https://github.com/anza-xyz/agave/blob/v2.0.4/Cargo.toml#L502-L533
[patch.crates-io.curve25519-dalek]
git = "https://github.com/anza-xyz/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"
